"""Orchestrator — routes requests and coordinates all agents."""
import json
import logging
from agents import (
    transcription_agent,
    language_detection_agent,
    translation_agent,
    quality_review_agent,
    keyboard_agent,
    conversation_agent,
)
import memory_store
import vocabulary_store

logger = logging.getLogger(__name__)
MAX_RETRIES = 1
_DETECT_OVERRIDE_MIN_LEN = 6


def _retrieval_context(text: str, source: str, target: str, vocab_ctx: str) -> tuple[str, int]:
    semantic_hits = memory_store.semantic_search(text, source, target)
    memory_ctx = memory_store.to_context([
        hit for hit in semantic_hits
        if hit.get("kind") == "translation_memory"
    ])
    semantic_vocab = []
    for hit in semantic_hits:
        if hit.get("kind") != "vocabulary" or not hit.get("term"):
            continue
        try:
            translations = json.loads(hit.get("translations_json") or "{}")
        except Exception:
            translations = {}
        preferred = translations.get(target, "")
        if preferred:
            semantic_vocab.append(f'  • "{hit["term"]}" → use exactly "{preferred}"')
        elif hit.get("definition"):
            semantic_vocab.append(f'  • "{hit["term"]}": {hit["definition"]}')
    semantic_vocab_ctx = (
        "Semantic terminology matches — apply when relevant:\n" + "\n".join(semantic_vocab[:5])
        if semantic_vocab else ""
    )
    parts = [part for part in (vocab_ctx, semantic_vocab_ctx, memory_ctx) if part]
    return "\n\n".join(parts), len(semantic_hits)


def _save_memory(text: str, translation: str, source: str, target: str) -> None:
    if text and translation and source != target:
        memory_store.add(text, translation, source, target)


def run_text_pipeline(text: str, source: str, target: str) -> dict:
    """Fast text pipeline (no quality review) — keeps real-time typing latency low.

    Language Detection → Enterprise Vocabulary lookup → Translation
    """
    detected = language_detection_agent.run(text)
    effective_source = detected if detected != source else source

    vocab_entries = vocabulary_store.search(text, effective_source)
    vocab_ctx = vocabulary_store.to_context(vocab_entries, target)
    vocab_ver = vocabulary_store.get_version()

    exact_memory = memory_store.find_exact(text, effective_source, target)
    if exact_memory:
        return {
            "original_text": text,
            "detected_language": detected,
            "translation": exact_memory["translated_text"],
            "vocab_hits": len(vocab_entries),
            "memory_hits": 1,
            "words": [],
        }

    retrieval_ctx, memory_hits = _retrieval_context(text, effective_source, target, vocab_ctx)
    translation = translation_agent.run(
        text, effective_source, target,
        vocab_context=retrieval_ctx, vocab_version=vocab_ver,
    )
    _save_memory(text, translation, effective_source, target)

    return {
        "original_text": text,
        "detected_language": detected,
        "translation": translation,
        "vocab_hits": len(vocab_entries),
        "memory_hits": memory_hits,
        "words": [],
    }


def run_conversation_pipeline(
    text: str,
    source: str,
    target: str,
    style_context: str = "",
) -> dict:
    """Per-participant conversation pipeline with full anti-hallucination guardrails.

    Conversation Agent (clean fillers) → Language Detection
    → Enterprise Vocabulary lookup
    → Strict Translation (70B, temp=0, voice-preserving with style_context)
    → Fast Quality Review (8B-instant) → Retry once with critique if flagged

    style_context is generated by style_profiler.to_prompt_hint() per speaker
    and injected verbatim into the translation prompt so the model mirrors the
    speaker's register and sentence rhythm rather than normalising to a generic
    translation voice.
    """
    cleaned = conversation_agent.run(text, source_lang=source)

    detected = language_detection_agent.run(cleaned)
    effective_source = (
        detected
        if detected != source and len(cleaned) >= _DETECT_OVERRIDE_MIN_LEN
        else source
    )

    vocab_entries = vocabulary_store.search(cleaned, effective_source)
    vocab_ctx = vocabulary_store.to_context(vocab_entries, target)
    vocab_ver = vocabulary_store.get_version()

    exact_memory = memory_store.find_exact(cleaned, effective_source, target)
    if exact_memory:
        return {
            "original_text": text,
            "cleaned_text": cleaned,
            "detected_language": detected,
            "translation": exact_memory["translated_text"],
            "quality": {"passed": True, "critique": "translation memory exact match"},
            "vocab_hits": len(vocab_entries),
            "memory_hits": 1,
        }

    retrieval_ctx, memory_hits = _retrieval_context(cleaned, effective_source, target, vocab_ctx)
    try:
        translation = translation_agent.run(
            cleaned, effective_source, target,
            strict=True,
            vocab_context=retrieval_ctx,
            vocab_version=vocab_ver,
            style_context=style_context,
        )
    except Exception as e:
        logger.error("Translation agent failed: %s", e)
        translation = cleaned

    review = {"passed": True, "critique": ""}
    for _ in range(MAX_RETRIES):
        try:
            review = quality_review_agent.run(cleaned, translation, effective_source, target)
        except Exception as e:
            logger.warning("Quality review failed (treating as pass): %s", e)
            review = {"passed": True, "critique": ""}
            break
        if review["passed"]:
            break
        try:
            translation = translation_agent.run(
                cleaned, effective_source, target,
                critique=review["critique"],
                strict=True,
                vocab_context=retrieval_ctx,
                vocab_version=vocab_ver,
                style_context=style_context,
            )
        except Exception as e:
            logger.error("Retry translation failed: %s", e)
            break

    _save_memory(cleaned, translation, effective_source, target)
    return {
        "original_text": text,
        "cleaned_text": cleaned,
        "detected_language": detected,
        "translation": translation,
        "quality": review,
        "vocab_hits": len(vocab_entries),
        "memory_hits": memory_hits,
    }


def run_keyboard_pipeline(text: str, source: str, target: str) -> dict:
    """Keyboard pipeline: Keyboard Agent → Language Detection → Translation."""
    cleaned = keyboard_agent.run(text)
    detected = language_detection_agent.run(cleaned)
    effective_source = detected if detected != source else source

    vocab_entries = vocabulary_store.search(cleaned, effective_source)
    vocab_ctx = vocabulary_store.to_context(vocab_entries, target)
    vocab_ver = vocabulary_store.get_version()

    exact_memory = memory_store.find_exact(cleaned, effective_source, target)
    if exact_memory:
        return {
            "original_text": cleaned,
            "detected_language": detected,
            "translation": exact_memory["translated_text"],
            "vocab_hits": len(vocab_entries),
            "memory_hits": 1,
        }

    retrieval_ctx, memory_hits = _retrieval_context(cleaned, effective_source, target, vocab_ctx)
    translation = translation_agent.run(
        cleaned, effective_source, target,
        vocab_context=retrieval_ctx, vocab_version=vocab_ver,
    )
    _save_memory(cleaned, translation, effective_source, target)
    return {
        "original_text": cleaned,
        "detected_language": detected,
        "translation": translation,
        "vocab_hits": len(vocab_entries),
        "memory_hits": memory_hits,
    }


def run_audio_pipeline(audio_file: str, source: str, target: str) -> dict:
    """Full audio pipeline with quality review and retry on failure.

    Transcription → Language Detection → Enterprise Vocabulary lookup
    → Translation → Quality Review → Retry if flagged
    """
    transcription = transcription_agent.run(audio_file)
    text = transcription["text"]
    words = transcription["words"]

    detected = language_detection_agent.run(text)
    effective_source = detected if detected != source else source

    vocab_entries = vocabulary_store.search(text, effective_source)
    vocab_ctx = vocabulary_store.to_context(vocab_entries, target)
    vocab_ver = vocabulary_store.get_version()

    exact_memory = memory_store.find_exact(text, effective_source, target)
    if exact_memory:
        return {
            "original_text": text,
            "detected_language": detected,
            "translation": exact_memory["translated_text"],
            "words": words,
            "quality": {"passed": True, "critique": "translation memory exact match"},
            "vocab_hits": len(vocab_entries),
            "memory_hits": 1,
        }

    retrieval_ctx, memory_hits = _retrieval_context(text, effective_source, target, vocab_ctx)
    translation = translation_agent.run(
        text, effective_source, target,
        vocab_context=retrieval_ctx, vocab_version=vocab_ver,
    )

    review = {"passed": True, "critique": ""}
    for _ in range(MAX_RETRIES):
        review = quality_review_agent.run(text, translation, effective_source, target)
        if review["passed"]:
            break
        translation = translation_agent.run(
            text, effective_source, target,
            critique=review["critique"],
            vocab_context=retrieval_ctx,
            vocab_version=vocab_ver,
        )

    _save_memory(text, translation, effective_source, target)
    return {
        "original_text": text,
        "detected_language": detected,
        "translation": translation,
        "words": words,
        "quality": review,
        "vocab_hits": len(vocab_entries),
        "memory_hits": memory_hits,
    }
