"""Translation Agent — translates text from source to target language.

Moat features baked in:
  • Enterprise vocabulary context injection (caller supplies a context block
    generated by vocabulary_store.to_context()).
  • Voice preservation — the prompt instructs the model to match the speaker's
    formality level, tone and sentence rhythm rather than normalising to a
    generic register.
  • Translation cache — exact (text, source, target, vocab_version) lookups
    return immediately; short TTL so vocabulary updates propagate quickly.
  • Adaptive model sizing — short phrases (<= 80 chars, no vocabulary) route to
    the fast 8B model; everything else uses 70B for accuracy.
"""
import os
import time
from threading import Lock

from groq import Groq

_client = None
_client_lock = Lock()


def _get_client() -> Groq:
    global _client
    with _client_lock:
        if _client is None:
            api_key = os.environ.get("GROQ_API_KEY")
            if not api_key:
                raise RuntimeError("GROQ_API_KEY environment variable is not set")
            _client = Groq(api_key=api_key)
    return _client


LANG_NAMES = {
    "en": "English", "es": "Spanish", "fr": "French", "de": "German",
    "it": "Italian", "pt": "Portuguese", "zh": "Chinese", "ja": "Japanese",
    "ko": "Korean", "ar": "Arabic", "ru": "Russian", "hi": "Hindi",
    "nl": "Dutch", "pl": "Polish", "tr": "Turkish", "tl": "Tagalog",
}

# ── Models ─────────────────────────────────────────────────────────────────────
_MODEL_FAST = "llama-3.1-8b-instant"       # ~50-80 ms  — short/simple phrases
_MODEL_ACCURATE = "llama-3.3-70b-versatile" # ~200-400 ms — complex / vocab-rich

_SHORT_TEXT_THRESHOLD = 80  # chars; below this, fast model is used when safe

# ── System prompts ─────────────────────────────────────────────────────────────
_SYSTEM_BASE = (
    "You are a professional real-time translation engine. "
    "Your ONLY job is to translate text faithfully and naturally. "
    "NEVER add, remove, or change information. "
    "NEVER add explanations, greetings, commentary, or cultural notes. "
    "Preserve the speaker's exact formality level, tone, and sentence rhythm — "
    "casual speech stays casual, formal speech stays formal, short punchy "
    "sentences stay short. "
    "Output ONLY the translated text — nothing else."
)

_SYSTEM_STRICT = _SYSTEM_BASE  # same quality bar; strictness controlled by temp=0

# ── Few-shot reference pairs ──────────────────────────────────────────────────
# Hand-curated source→target examples per language direction, injected verbatim
# into the user prompt as anchor cases. Targets common false-friends, idioms,
# and lower-resource-language failures (e.g. Tagalog "papasyal" → "hallucinate").
# Add more pairs over time; the dict is keyed by (source, target).
_FEW_SHOT: dict[tuple[str, str], list[tuple[str, str]]] = {
    ("tl", "en"): [
        ("Kailan ka papasyal?", "When will you visit?"),
        ("Magkano ang pamasahe?", "How much is the fare?"),
        ("Ano na ang pangalan mo?", "What's your name now?"),
        ("Tapos na akong pinagpupulungan.", "I'm done being talked about."),
        ("Saan ka pupunta?", "Where are you going?"),
    ],
    ("en", "tl"): [
        ("When will you visit?", "Kailan ka papasyal?"),
        ("How much is the fare?", "Magkano ang pamasahe?"),
        ("Where are you going?", "Saan ka pupunta?"),
        ("Please wait a moment.", "Pakihintay ng sandali."),
    ],
    ("ja", "en"): [
        ("お元気ですか？", "How are you?"),
        ("申し訳ありません。", "I'm sorry."),
        ("もう一度お願いします。", "Could you say that again, please?"),
    ],
    ("en", "ja"): [
        ("Could you say that again, please?", "もう一度お願いします。"),
        ("Nice to meet you.", "はじめまして。"),
        ("I don't understand.", "わかりません。"),
    ],
    ("ko", "en"): [
        ("안녕하세요.", "Hello."),
        ("다시 말씀해 주세요.", "Please say that again."),
        ("잘 모르겠어요.", "I'm not sure."),
    ],
    ("en", "ko"): [
        ("Please say that again.", "다시 말씀해 주세요."),
        ("I don't understand.", "이해가 안 돼요."),
    ],
    ("ar", "en"): [
        ("كيف حالك؟", "How are you?"),
        ("من فضلك أعد ما قلت.", "Please repeat what you said."),
    ],
    ("en", "ar"): [
        ("Please repeat what you said.", "من فضلك أعد ما قلت."),
        ("Nice to meet you.", "تشرفت بلقائك."),
    ],
    ("hi", "en"): [
        ("आप कैसे हैं?", "How are you?"),
        ("कृपया दोबारा कहें।", "Please say that again."),
    ],
    ("en", "hi"): [
        ("Please say that again.", "कृपया दोबारा कहें।"),
        ("I don't understand.", "मुझे समझ नहीं आया।"),
    ],
    ("zh", "en"): [
        ("你好吗？", "How are you?"),
        ("请再说一遍。", "Please say that again."),
    ],
    ("en", "zh"): [
        ("Please say that again.", "请再说一遍。"),
        ("Nice to meet you.", "很高兴认识你。"),
    ],
    ("tr", "en"): [
        ("Nasılsın?", "How are you?"),
        ("Tekrar söyler misin?", "Could you say that again?"),
    ],
    ("en", "tr"): [
        ("Could you say that again?", "Tekrar söyler misin?"),
    ],
}


def _few_shot_block(source: str, target: str) -> str:
    pairs = _FEW_SHOT.get((source, target))
    if not pairs:
        return ""
    src_name = LANG_NAMES.get(source, source)
    tgt_name = LANG_NAMES.get(target, target)
    lines = [f"Reference {src_name} → {tgt_name} translations (anchor cases):"]
    for src, tgt in pairs:
        lines.append(f'  • "{src}" → "{tgt}"')
    return "\n".join(lines)


# ── Translation cache ─────────────────────────────────────────────────────────
# Key: (text_norm, source, target, vocab_version)
# Value: (translated_text, monotonic_timestamp)
_cache: dict[tuple, tuple[str, float]] = {}
_cache_lock = Lock()
_CACHE_TTL = 300.0   # 5 minutes — short enough that vocabulary updates take effect quickly
_CACHE_MAX = 2000


def _cache_key(text: str, source: str, target: str, vocab_version: int) -> tuple:
    return (text.strip().lower(), source, target, vocab_version)


def _cache_get(key: tuple) -> str | None:
    with _cache_lock:
        entry = _cache.get(key)
        if entry and (time.monotonic() - entry[1]) < _CACHE_TTL:
            return entry[0]
        if entry:
            del _cache[key]
    return None


def _cache_set(key: tuple, value: str) -> None:
    with _cache_lock:
        if len(_cache) >= _CACHE_MAX:
            # Evict oldest 20 %
            cutoff = time.monotonic() - _CACHE_TTL
            stale = [k for k, v in _cache.items() if v[1] < cutoff]
            for k in stale[:max(1, _CACHE_MAX // 5)]:
                del _cache[k]
        _cache[key] = (value, time.monotonic())


def cache_size() -> int:
    with _cache_lock:
        return len(_cache)


# ── Public entry point ─────────────────────────────────────────────────────────

def run(
    text: str,
    source: str,
    target: str,
    critique: str = "",
    strict: bool = False,
    vocab_context: str = "",
    vocab_version: int = 0,
    style_context: str = "",
) -> str:
    """Translate *text* from *source* language to *target* language.

    Args:
        text:          Source text.
        source:        ISO-639-1 source language code.
        target:        ISO-639-1 target language code.
        critique:      Quality-review critique from a previous attempt (triggers retry).
        strict:        Use temp=0 for maximum determinism (conversation pipeline).
        vocab_context: Enterprise terminology block from vocabulary_store.to_context().
        vocab_version: Vocabulary store version at call time (cache key component).
        style_context: Speaker voice-style hint from style_profiler.to_prompt_hint().
    """
    if not text.strip():
        return text

    if source == target:
        return text

    # Cache key incorporates style fingerprint so profile changes invalidate it.
    # Style context is short enough to hash cheaply by identity.
    style_key = hash(style_context) if style_context else 0

    if not critique:
        key = _cache_key(text, source, target, vocab_version) + (style_key,)
        cached = _cache_get(key)
        if cached:
            return cached

    client = _get_client()
    source_name = LANG_NAMES.get(source, source)
    target_name = LANG_NAMES.get(target, target)

    parts = [f"Translate the following text from {source_name} to {target_name}."]

    # Voice preservation — inject style hint when available
    if style_context:
        parts.append(style_context)
    else:
        parts.append("Preserve the speaker's formality, tone, and sentence rhythm.")

    few_shot = _few_shot_block(source, target)
    if few_shot:
        parts.append("")
        parts.append(few_shot)
        parts.append("")
    if vocab_context:
        parts.append("")
        parts.append(vocab_context)
        parts.append("")
    if critique:
        parts.append(f"A previous translation was flagged: {critique}. Fix those issues.")
    parts.append("")
    parts.append("Text to translate:")
    parts.append(text)
    prompt = "\n".join(parts)

    messages = [
        {"role": "system", "content": _SYSTEM_STRICT if strict else _SYSTEM_BASE},
        {"role": "user", "content": prompt},
    ]

    # Adaptive model routing: fast 8B for short/simple, accurate 70B otherwise.
    # strict=True (conversation pipeline) always forces the accurate model —
    # the 8B model mistranslates lower-resource languages like Tagalog
    # ("papasyal" → "hallucinate" instead of "visit").
    use_fast = (
        not strict
        and not vocab_context
        and not style_context
        and not critique
        and len(text.strip()) <= _SHORT_TEXT_THRESHOLD
    )
    model = (
        os.environ.get("GROQ_MODEL_FAST", _MODEL_FAST) if use_fast
        else os.environ.get("GROQ_MODEL", _MODEL_ACCURATE)
    )

    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0 if strict else 0.2,
        max_tokens=1024,
    )
    result = response.choices[0].message.content.strip()

    if not critique:
        full_key = _cache_key(text, source, target, vocab_version) + (style_key,)
        _cache_set(full_key, result)

    return result
