"""Translation Agent — translates text from source to target language.

Moat features baked in:
  • Enterprise vocabulary context injection (caller supplies a context block
    generated by vocabulary_store.to_context()).
  • Voice preservation — the prompt instructs the model to match the speaker's
    formality level, tone and sentence rhythm rather than normalising to a
    generic register.
  • Translation cache — exact (text, source, target, vocab_version) lookups
    return immediately; short TTL so vocabulary updates propagate quickly.
  • Adaptive model sizing — short phrases (<= 80 chars, no vocabulary) route to
    the fast 8B model; everything else uses 70B for accuracy.
"""
import os
import time
from threading import Lock

from groq import Groq

_client = None
_client_lock = Lock()


def _get_client() -> Groq:
    global _client
    with _client_lock:
        if _client is None:
            api_key = os.environ.get("GROQ_API_KEY")
            if not api_key:
                raise RuntimeError("GROQ_API_KEY environment variable is not set")
            _client = Groq(api_key=api_key)
    return _client


LANG_NAMES = {
    "en": "English", "es": "Spanish", "fr": "French", "de": "German",
    "it": "Italian", "pt": "Portuguese", "zh": "Chinese", "ja": "Japanese",
    "ko": "Korean", "ar": "Arabic", "ru": "Russian", "hi": "Hindi",
    "nl": "Dutch", "pl": "Polish", "tr": "Turkish", "tl": "Tagalog",
}

# ── Models ─────────────────────────────────────────────────────────────────────
_MODEL_FAST = "llama-3.1-8b-instant"       # ~50-80 ms  — short/simple phrases
_MODEL_ACCURATE = "llama-3.3-70b-versatile" # ~200-400 ms — complex / vocab-rich

_SHORT_TEXT_THRESHOLD = 80  # chars; below this, fast model is used when safe

# ── System prompts ─────────────────────────────────────────────────────────────
_SYSTEM_BASE = (
    "You are a professional real-time translation engine. "
    "Your ONLY job is to translate text faithfully and naturally. "
    "NEVER add, remove, or change information. "
    "NEVER add explanations, greetings, commentary, or cultural notes. "
    "Preserve the speaker's exact formality level, tone, and sentence rhythm — "
    "casual speech stays casual, formal speech stays formal, short punchy "
    "sentences stay short. "
    "Output ONLY the translated text — nothing else."
)

_SYSTEM_STRICT = _SYSTEM_BASE  # same quality bar; strictness controlled by temp=0

# ── Translation cache ─────────────────────────────────────────────────────────
# Key: (text_norm, source, target, vocab_version)
# Value: (translated_text, monotonic_timestamp)
_cache: dict[tuple, tuple[str, float]] = {}
_cache_lock = Lock()
_CACHE_TTL = 300.0   # 5 minutes — short enough that vocabulary updates take effect quickly
_CACHE_MAX = 2000


def _cache_key(text: str, source: str, target: str, vocab_version: int) -> tuple:
    return (text.strip().lower(), source, target, vocab_version)


def _cache_get(key: tuple) -> str | None:
    with _cache_lock:
        entry = _cache.get(key)
        if entry and (time.monotonic() - entry[1]) < _CACHE_TTL:
            return entry[0]
        if entry:
            del _cache[key]
    return None


def _cache_set(key: tuple, value: str) -> None:
    with _cache_lock:
        if len(_cache) >= _CACHE_MAX:
            # Evict oldest 20 %
            cutoff = time.monotonic() - _CACHE_TTL
            stale = [k for k, v in _cache.items() if v[1] < cutoff]
            for k in stale[:max(1, _CACHE_MAX // 5)]:
                del _cache[k]
        _cache[key] = (value, time.monotonic())


def cache_size() -> int:
    with _cache_lock:
        return len(_cache)


# ── Public entry point ─────────────────────────────────────────────────────────

def run(
    text: str,
    source: str,
    target: str,
    critique: str = "",
    strict: bool = False,
    vocab_context: str = "",
    vocab_version: int = 0,
) -> str:
    """Translate *text* from *source* language to *target* language.

    Args:
        text:          Source text.
        source:        ISO-639-1 source language code.
        target:        ISO-639-1 target language code.
        critique:      Quality-review critique from a previous attempt (triggers retry).
        strict:        Use temp=0 for maximum determinism (conversation pipeline).
        vocab_context: Enterprise terminology block from vocabulary_store.to_context().
        vocab_version: Vocabulary store version at call time (cache key component).
    """
    if not text.strip():
        return text

    if source == target:
        return text

    # Cache lookup (skip on retry — critique implies the first result was bad)
    if not critique:
        key = _cache_key(text, source, target, vocab_version)
        cached = _cache_get(key)
        if cached:
            return cached

    client = _get_client()
    source_name = LANG_NAMES.get(source, source)
    target_name = LANG_NAMES.get(target, target)

    # Build the user prompt
    parts = [
        f"Translate the following text from {source_name} to {target_name}.",
        "Preserve the speaker's formality, tone, and sentence rhythm.",
    ]
    if vocab_context:
        parts.append("")
        parts.append(vocab_context)
        parts.append("")
    if critique:
        parts.append(f"A previous translation was flagged: {critique}. Fix those issues.")
    parts.append("")
    parts.append("Text to translate:")
    parts.append(text)
    prompt = "\n".join(parts)

    messages = [
        {"role": "system", "content": _SYSTEM_STRICT if strict else _SYSTEM_BASE},
        {"role": "user", "content": prompt},
    ]

    # Adaptive model: skip 70B for very short phrases with no vocabulary context
    use_fast = (
        not vocab_context
        and not critique
        and len(text.strip()) <= _SHORT_TEXT_THRESHOLD
    )
    model = (
        os.environ.get("GROQ_MODEL_FAST", _MODEL_FAST) if use_fast
        else os.environ.get("GROQ_MODEL", _MODEL_ACCURATE)
    )

    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0 if strict else 0.2,
        max_tokens=1024,
    )
    result = response.choices[0].message.content.strip()

    # Cache successful (non-retry) results
    if not critique:
        _cache_set(_cache_key(text, source, target, vocab_version), result)

    return result
